In [116]:
import pandas as pd 
import numpy as np 
from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
import matplotlib.pyplot as plt
import seaborn as sns

In [117]:
data = pd.read_csv("https://raw.githubusercontent.com/4GeeksAcademy/regularized-linear-regression-project-tutorial/main/demographic_health_data.csv")

In [118]:
data

,fips,TOT_POP,0-9,0-9 y/o % of total pop,19-Oct,10-19 y/o % of total pop,20-29,20-29 y/o % of total pop,30-39,30-39 y/o % of total pop,...,COPD_number,diabetes_prevalence,diabetes_Lower 95% CI,diabetes_Upper 95% CI,diabetes_number,CKD_prevalence,CKD_Lower 95% CI,CKD_Upper 95% CI,CKD_number,Urban_rural_code
0,1001,55601,6787,12.206615,7637,13.735364,6878,12.370281,7089,12.749771,...,3644,12.9,11.9,13.8,5462,3.1,2.9,3.3,1326,3
1,1003,218022,24757,11.355276,26913,12.344167,23579,10.814964,25213,11.564429,...,14692,12.0,11.0,13.1,20520,3.2,3.0,3.5,5479,4
2,1005,24881,2732,10.980266,2960,11.896628,3268,13.134520,3201,12.865239,...,2373,19.7,18.6,20.6,3870,4.5,4.2,4.8,887,6
3,1007,22400,2456,10.964286,2596,11.589286,3029,13.522321,3113,13.897321,...,1789,14.1,13.2,14.9,2511,3.3,3.1,3.6,595,2
4,1009,57840,7095,12.266598,7570,13.087828,6742,11.656293,6884,11.901798,...,4661,13.5,12.6,14.5,6017,3.4,3.2,3.7,1507,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3135,56037,43051,6104,14.178532,6326,14.694200,5359,12.448027,6577,15.277229,...,2098,8.9,8.3,9.6,2834,2.6,2.4,2.8,821,5
3136,56039,23081,2384,10.328842,2185,9.466661,2967,12.854729,4093,17.733200,...,928,7.2,6.5,8.0,1360,2.4,2.2,2.6,447,5
3137,56041,20299,3121,15.375142,3205,15.788955,2153,10.606434,2702,13.311001,...,1163,10.4,9.5,11.2,1500,3.0,2.8,3.2,430,5
3138,56043,7885,858,10.881420,1113,14.115409,715,9.067850,903,11.452124,...,506,11.3,10.3,12.1,686,3.4,3.2,3.7,207,6
3139,56045,6967,780,11.195637,779,11.181283,681,9.774652,906,13.004162,...,480,11.7,10.7,12.7,644,3.4,3.1,3.6,185,6

In [119]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3140 entries, 0 to 3139
Columns: 108 entries, fips to Urban_rural_code
dtypes: float64(61), int64(45), object(2)
memory usage: 2.6+ MB

In [120]:
data.isna().sum()

fips                      0
TOT_POP                   0
0-9                       0
0-9 y/o % of total pop    0
19-Oct                    0
                         ..
CKD_prevalence            0
CKD_Lower 95% CI          0
CKD_Upper 95% CI          0
CKD_number                0
Urban_rural_code          0
Length: 108, dtype: int64

In [121]:
data.describe().round(2)

,fips,TOT_POP,0-9,0-9 y/o % of total pop,19-Oct,10-19 y/o % of total pop,20-29,20-29 y/o % of total pop,30-39,30-39 y/o % of total pop,...,COPD_number,diabetes_prevalence,diabetes_Lower 95% CI,diabetes_Upper 95% CI,diabetes_number,CKD_prevalence,CKD_Lower 95% CI,CKD_Upper 95% CI,CKD_number,Urban_rural_code
count,3140.00,3140.00,3140.0,3140.00,3140.00,3140.00,3140.00,3140.00,3140.00,3140.00,...,3140.00,3140.00,3140.00,3140.00,3140.00,3140.00,3140.00,3140.00,3140.00,3140.00
mean,30401.64,104189.41,12740.3,11.87,13367.98,12.69,14469.33,12.28,13916.49,11.75,...,5827.24,13.07,12.09,14.05,9326.58,3.45,3.21,3.71,2466.23,4.64
std,15150.56,333583.40,41807.3,2.12,42284.39,1.82,49577.73,3.13,48990.95,1.70,...,15720.55,2.72,2.62,2.82,29754.60,0.57,0.53,0.61,7730.42,1.51
min,1001.00,88.00,0.0,0.00,0.00,0.00,0.00,0.00,11.00,6.09,...,7.00,6.10,5.50,6.70,11.00,1.80,1.70,1.90,3.00,1.00
25%,18180.50,10963.25,1280.5,10.59,1374.50,11.67,1263.75,10.50,1232.75,10.69,...,815.00,11.20,10.30,12.10,1187.75,3.10,2.90,3.30,314.75,3.00
50%,29178.00,25800.50,3057.0,11.80,3274.00,12.69,3108.00,11.77,3000.50,11.58,...,1963.50,12.80,11.80,13.80,2743.00,3.40,3.20,3.70,718.00,5.00
75%,45081.50,67913.00,8097.0,12.95,8822.25,13.66,8976.25,13.18,8314.25,12.64,...,4727.00,14.80,13.70,15.90,6679.25,3.80,3.50,4.10,1776.25,6.00
max,56045.00,10105518.00,1208253.0,25.46,1239139.00,23.30,1557073.00,37.57,1501844.00,22.23,...,434075.00,25.60,24.20,27.00,952335.00,6.20,5.80,6.60,237766.00,6.00

In [122]:
data.columns

Index(['fips', 'TOT_POP', '0-9', '0-9 y/o % of total pop', '19-Oct',
       '10-19 y/o % of total pop', '20-29', '20-29 y/o % of total pop',
       '30-39', '30-39 y/o % of total pop',
       ...
       'COPD_number', 'diabetes_prevalence', 'diabetes_Lower 95% CI',
       'diabetes_Upper 95% CI', 'diabetes_number', 'CKD_prevalence',
       'CKD_Lower 95% CI', 'CKD_Upper 95% CI', 'CKD_number',
       'Urban_rural_code'],
      dtype='object', length=108)

In [123]:
data = pd.get_dummies(data)

In [124]:
X_train = data.drop(["Heart disease_number"], axis = 1)
y_train = data["Heart disease_number"]
X_test = data.drop(["Heart disease_number"], axis = 1)
y_test = data["Heart disease_number"]

In [125]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [126]:
print(f"Intercept (a): {model.intercept_}")
print(f"Coefficients (b): {model.coef_}")

Intercept (a): -7038.528278552568
Coefficients (b): [ 5.86900802e-03  2.18465749e-02  6.96063104e-02 ...  5.21970945e+02
 -1.78543318e+02  9.62122926e+01]

In [127]:
y_pred = model.predict(X_test)
y_pred

array([ 3345.00000094, 13554.73130169,  2261.71304061, ...,
        1033.99999894,   499.99999938,   470.99999933], shape=(3140,))

In [128]:
from sklearn.metrics import mean_squared_error, r2_score

print(f"Mean squared error: {mean_squared_error(y_test, y_pred)}")
print(f"Coefficient of determination: {r2_score(y_test, y_pred)}")

Mean squared error: 17530.13654291547
Coefficient of determination: 0.9999280842898646

In [135]:
from sklearn.linear_model import Lasso

 #Load of train and test data
 #These data must have been standardized and correctly processed in a complete EDA


lasso_model = Lasso(alpha = 0.1, max_iter = 300)

lasso_model.fit(X_train, y_train)

y_pred = lasso_model.predict(X_test)

y_pred

/home/codespace/.local/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.910e+08, tolerance: 7.654e+07
  model = cd_fast.enet_coordinate_descent(

array([ 3290.97804531, 14005.55472728,  2293.55460798, ...,
         907.30611693,   392.99179616,   499.36333313], shape=(3140,))

In [132]:
from sklearn.linear_model import Ridge  

# Load of train and test data  
# These data must have been standardized and correctly processed in a complete EDA  

# Assuming X_train and y_train are already defined  
ridge_model = Ridge(alpha=0.1, max_iter=300)  

# Fit the model on the training data  
ridge_model.fit(X_train, y_train)  

# Predict using the test features  
y_pred = ridge_model.predict(X_test)  # Use X_test for predictions

y_pred

/home/codespace/.local/lib/python3.12/site-packages/sklearn/linear_model/_ridge.py:215: LinAlgWarning: Ill-conditioned matrix (rcond=1.53029e-17): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

array([ 3352.18225173, 13591.42284302,  2251.12985375, ...,
        1034.0414426 ,   496.7905156 ,   473.5879599 ], shape=(3140,))